### ISSUE TITLE
Mixin with variable amount of arguments doesn't work

### ISSUE THREAD

**Issue by kottenator** [Kronuz/pyScss#100]
Next declaration:

``` scss
@mixin box-shadow($shadows...) {
    box-shadow: $shadows;
}

.shadows {
    @include box-shadow(0px 4px 5px #666, 2px 6px 10px #999);
}
```

is compiled to:

``` scss
.shadows {
    box-shadow: $shadows;
}
```

when expected result is:

``` scss
.shadows {
    box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
}
```
