### ISSUE TITLE
Child and adjacent sibling selectors broken

### ISSUE THREAD

**Issue by ghost** [Kronuz/pyScss#103]
run with "scss -m base.scss base.css"

``` css
.marketing {
  > p {
    margin-top: 28px;
  }
}
```

.marketing {
^
Expected end of text (at char 373), (line:36, col:1)

``` css
p {
  + h4 {
    margin-top: 28px;
  }
}
```

p {
  ^
Expected end of text (at char 375), (line:36, col:3)
