### ISSUE TITLE
You cannot redeclare the value of a global variable inside a @mixin.

### ISSUE THREAD

**Issue by zalun** [Kronuz/pyScss#110]
Issue created on JSFiddle issues page:
https://github.com/jsfiddle/jsfiddle-issues/issues/197

Example:

``` scss
$global: blue;

@mixin box {
  $global: red;
  color: $global; 
}

p { @include box() }
```

Expected:

``` css
p { color: red }
```

Actual:

``` css
p { blue: red; color: blue; }
```

Instead of reassigning red to the $global variable, it echos the value of the variable.
