### ISSUE TITLE
Wrapping output on whitespace in quotes breaks certain CSS on IE8 and 9.

### ISSUE THREAD

**Issue by bjornars** [Kronuz/pyScss#122]
Ex. from bootstrap-sass:

``` css
.icon-white,
.nav-pills > .active > a > [class^="icon-"],
.nav-pills > .active > a > [class*=" icon-"],
.nav-list > .active > a > [class^="icon-"],
.nav-list > .active > a > [class*=" icon-"],
.navbar-inverse .nav > .active > a > [class^="icon-"],
.navbar-inverse .nav > .active > a > [class*=" icon-"],
.dropdown-menu > li > a:hover > [class^="icon-"],
.dropdown-menu > li > a:focus > [class^="icon-"],
.dropdown-menu > li > a:hover > [class*=" icon-"],
.dropdown-menu > li > a:focus > [class*=" icon-"],
.dropdown-menu > .active > a > [class^="icon-"],
.dropdown-menu > .active > a > [class*=" icon-"],
.dropdown-submenu:hover > a > [class^="icon-"],
.dropdown-submenu:focus > a > [class^="icon-"],
.dropdown-submenu:hover > a > [class*=" icon-"],
.dropdown-submenu:focus > a > [class*=" icon-"] {
  background-image: url($iconWhiteSpritePath);
}
```

This will get compiled into one of the lines ending with an unterminated quote, and will cause the rest of the file to be ignored by IE8 and IE9, like this:

``` css
.icon-white,
.nav-pills > .active > a > [class^="icon-"], .nav-pills > .active > a > [class*="
icon-"], .nav-list > .active > a > [class^="icon-"],
<snip>] {
  background-image: url($iconWhiteSpritePath);
}
```

A workaround is to enable minifying.
