### ISSUE TITLE
Underscores in @function names replaced with dashes

### ISSUE THREAD

**Issue by ghost** [Kronuz/pyScss#162]
Although this looks intentional, it is not documented anywhere that I could see, and seems like bad behavior. As far as I could tell, it doesn't match Ruby's implementation of SCSS.

Anyways, With a file like so:

``` SCSS
@function funca {
  @return '10px';
}

@function func_b() {
  @return '10px';
}

.asdf {
  height: funca();
  width: func_b();
} 
```

I get 

``` SCSS
ERROR: Required function not found: func-b:0 (<string "@function funca {\n  @return '10px';\n}\n\n@function f...">:9)
.asdf {
  height: 10px;
  width: func_b();
}
```

which is not what I'd expect. In __init__.py on line 5000, there's this line of code:

``` Python
    _name = name.replace('_', '-')
```

changing that line to 

``` Python
    _name = name
```

fixes the problem, but changes what looks to be an intentional stripping of underscores. What exactly is that line trying to accomplish?
