### ISSUE TITLE
Behavior of font-files differs from Compass

### ISSUE THREAD

**Issue by pferreir** [Kronuz/pyScss#170]
Example:

``` scss
@import "compass/css3";

@include font-face("icomoon-ultimate", 
        font-files("../fonts/icomoon.woff",
                   "../fonts/icomoon.eot",
                   "../fonts/icomoon.ttf",
                   "../fonts/icomoon.svg"));
```

Compass output:

``` css
@font-face {
  font-family: "icomoon-ultimate";
  src: url('/stylesheets/fonts/../fonts/icomoon.woff') format('woff'),
       url('/stylesheets/fonts/../fonts/icomoon.eot') format('embedded-opentype'),
       url('/stylesheets/fonts/../fonts/icomoon.ttf') format('truetype'),
       url('/stylesheets/fonts/../fonts/icomoon.svg') format('svg');
}
```

PySCSS output:

``` css
@font-face {
  font-family: "icomoon-ultimate";
  src: url("/static/../fonts/icomoon.woff?_=NA")
    format("../fonts/icomoon.eot")
    url("/static/../fonts/icomoon.ttf?_=NA")
    format("../fonts/icomoon.svg");
}
```
