### ISSUE TITLE
trouble with @font-face format

### ISSUE THREAD

**Issue by vindolin** [Kronuz/pyScss#23]
``` css
@font-face {
  font-family: 'Maiden Orange';
  font-style: normal;
  font-weight: normal;
  src: local('Maiden Orange'), local('MaidenOrange-Regular'), url('/static/fonts/MaidenOrange.woff') format('woff');
}
```

gets parsed to

``` css
@font-face {
  font-family: Maiden Orange;
  font-style: normal;
  font-weight: normal;
  src: local(Maiden Orange), local(MaidenOrange-Regular),
    url(/static/fonts/MaidenOrange.woff) format(woff);
}
```

The problem is that "format(woff)" without the quotes around woff is not recognized by firefox/chrome.
