### ISSUE TITLE
unused placeholder selectors not cleaned up

### ISSUE THREAD

**Issue by ktmud** [Kronuz/pyScss#245]
``` sass
%foo {
  display: block;
}
%bar {
  display: inline;
}

.foo-kid {
  @extend %foo;
}
```

The unused placeholder selector `%bar` should be dropped. 

But the output ends up with:

``` css
.foo-kid {
  display: block;
}
 {
  display: inline;
}
```

An empty selector generated.
