### ISSUE TITLE
&:after failed when using @extend

### ISSUE THREAD

**Issue by ktmud** [Kronuz/pyScss#246]
``` sass
%a {
  &:after {
      content: '\a';
  }
}
.a-kid {
  @extend %a;
}
```

Expected result:

``` css
.a-kid:after {
  content: '\a';
}
```

Got:

``` css
:after.a-kid {
  content: '\a';
}
```
