### ISSUE TITLE
CSS selector with ':'

### ISSUE THREAD

**Issue by ninfaj** [Kronuz/pyScss#273]
Hi there!
It's not possible (or I didn't find out how) to define a CSS selector for elements with a `':' or '\3A' (CSS)` in the class (for example `<div class="width1:4">test</div>`).

```
python
from scss import Scss
compiler = Scss()
compiler.compile('div.width1\3A 4 {width: 25%;}')
```

This will return

``` css
div\x03A.width1 4 {
  width: 25%;
}
```

But imho it should return 

``` css
div.width1\3A 4 {
  width: 25%;
}
```

Is there a possibility to escape the `\`?
