### ISSUE TITLE
@extend doesn't work with &:after

### ISSUE THREAD

**Issue by nottrobin** [Kronuz/pyScss#309]
``` scss
.test {
    &:after {
        display: block;
        content: "hello world";
        height: 200px;
        width: 200px;
        background-color: blue;
    }
}

.test-extender {
    @extend .test;
}
```

In the above example, any element with the class `test-extender` won't get the `:after` pseudo-element properly when compiled with pyScss, but it will when compiled with SASS.

Tested with `v1.2.0.post3` and `v1.2.1`.
