### ISSUE TITLE
Loss of precision for rgba

### ISSUE THREAD

**Issue by asottile** [Kronuz/pyScss#329]
Input:
```scss
a {
    color: rgba(0, 0, 0, 0.125);
}
```
Output:

```css
a{color:rgba(0,0,0,0.12)}
```

Expected:

```css
a{color:rgba(0,0,0,0.125)}
```
