### ISSUE TITLE
Floor of subtraction of integer pixels rounding bug

### ISSUE THREAD

**Issue by asottile** [Kronuz/pyScss#330]
```scss
a { width: floor(742px - 40px);}
```
Expected:
```css
a{width:702px}
```
Actual:
```css
a{width:701px}
```
