### ISSUE TITLE
null variables are not stripped from output

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [Kronuz/pyScss#337]
```scss
body {
    $color: null;
    color: $color;
}
```

includes the `color: null` rule.  It should be stripped.
