### ISSUE TITLE
Expressions do not work in media queries

### ISSUE THREAD

**Issue by matharden** [Kronuz/pyScss#347]
The following code should evaluate the variable expression

```scss
$breakpoint: 480px;

@media (max-width: $breakpoint - 1) {
  main {
    color: red;
  }
}
```

to output this CSS…

```css
@media (max-width: 479px) {
  main {
    color: red;
  }
}
```

but instead results in the following invalid CSS…

```css
@media (max-width: 480px - 1) {
  main {
    color: red;
  }
}
```

My current work-around is to use interpolation…

```scss
$breakpoint: 480px;

@media (max-width: #{$breakpoint - 1}) {
  main {
    color: red;
  }
}
```
