### ISSUE TITLE
darken() compiles to an invalid CSS color

### ISSUE THREAD

**Issue by jtuulos** [Kronuz/pyScss#35]
I'm having problems with the following SCSS code:

``` scss
$blueDark: #0064CD;
$linkColor: $blueDark;
$linkColorHover: darken($linkColor, 15%);

a:hover {
    color: $linkColorHover;
}
```

In the compiled CSS, the color value is invalid and ends up getting ignored by the browser (Chrome):

``` css
a:hover {
    color: rgb(0, 24.582%, 50.392%)
}
```

As you can see, a percentage mark is missing after the red color value.

Is there a possibility to compile all colors with no alpha channel to regular hex colors (and not rgb() with percentages)?
