### ISSUE TITLE
Single quotes in property values not preserved

### ISSUE THREAD

**Issue by benjamn** [Kronuz/pyScss#50]
CSS such as this

``` css
div {
  label: 'a b';
}
```

is being compiled to this

``` css
div{label:a b}
```

when this

``` css
div{label:'a b'}
```

is what should be produced.
