### ISSUE TITLE
Expand variables before parsing function parameters

### ISSUE THREAD

**Issue by QuLogic** [Kronuz/pyScss#61]
In compass, there's a function in grid-background that does something like:

``` scss
  @for $i from 0 to $total {
    // do stuff
    $grid: join($grid, ($column-color $a, $column-color $g));
  }
  // other stuff...
  $gradient: linear-gradient(left, $grid);
```

To pyScss, it thinks that there are only two parameters to `linear-gradient`, but with the ruby parser, `$grid` seems to be expanded first, and then the function parameters are determined. The problem with pyScss's version is that the `linear-gradient` code can no longer find any colour-stops and outputs garbage.
