### ISSUE TITLE
Expand mixin default values at use-time

### ISSUE THREAD

**Issue by QuLogic** [Kronuz/pyScss#66]
Something like the following:

``` scss
$foo: black;

@mixin test($param: $foo) {
  color: $param;
}

$foo: green;
body {
  @include test;
}
```

will result in:

``` css
/* Generated from: test.scss */
body {
  color: #000000;
}
```

but the Ruby parser outputs:

``` css
body {
  color: green; }
```

Ignoring the change to hex, pyScss outputs the wrong colour.
