### ISSUE TITLE
media queries are duplicated

### ISSUE THREAD

**Issue by fschulze** [Kronuz/pyScss#69]
I added a test in my branch https://github.com/fschulze/pyScss/tree/media-query-splitting which shows, that media queries are duplicated. This:

``` css
@media (max-width:1024px) {
  body {
    background: red;
  }
  div {
    background: blue;
  }
}
```

Currently becomes this:

``` css
@media (max-width:1024px) {
  body {
    background: #ff0000;
  }
}
@media (max-width:1024px) {
  div {
    background: #0000ff;
  }
}
```

But should be this:

``` css
@media (max-width:1024px) {
  body {
    background: #ff0000;
  }
  div {
    background: #0000ff;
  }
}
```

I tried to fix it myself, but have no clue what is going on in the code.
