### ISSUE TITLE
Product of a number and a undefined variable duplicates variable name

### ISSUE THREAD

**Issue by alvra** [Kronuz/pyScss#91]
When multiplying a variable that holds a number `$n` and an undefined variable, the results is the name of the variable duplicated `$n` times. This is what you'd get in python when multiplying the variable name string with the number.

I'd expect it to throw an error or generate a log message for the unknown variable, or at least return some valid css.

When the variable `$n` isn't defined either, you do get a log message.
However, this leaves the multiplication untouched as `$n * $colsize`, which is invalid css.

The scss:

``` scss
$n: 2;
div {
  left: $n * $colsize;
}
```

The result:

``` css
div {
  left: $colsize$colsize
}
```
